name: fl_animated_linechart
description: Animated flutter line & area chart. Performs with big datasets, support multiple y axis and datetime x axis
version: 1.1.4
homepage: https://github.com/umbrew/fl_animated_linechart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
